#! /bin/bash

# Maker/tester/runner for the experimental version of Fizz.
# Usage: ./run.sh r|t e|p|n|h 1|2[|h-opts]
# Mods:
# r - run; run Viewer from /data/ with options from e|p|n|h
# t - test; make Viewer, used to see if there are any compile time errors
# e - eventlog; compiles and runs the file with eventlog enabled
# p - profile; compiles and runs the file with profiling enabled
# n - neither profiling nor eventlog is enabled
# h - runs the program with heap profiling, converts output to a .ps file.
#     For this option third arg is an extra arg for heap profile, i.e. -h[arg]
# 1|2 - number of cores in execution, from ghc's -N*
#
# Examples:
# ./run t - test, compile with no optimization
# ./run r e 2, compile+run with eventlong enabled, two cores

cd ~/Dropbox/Work/Fizz
if [ "$1" = "r" ]
then
    MAKESTRING="ghc Viewer.hs -O2 -rtsopts -threaded"
    RUNSTRING="../Viewer +RTS -s -K200M"
elif [ "$1" = "t" ]
then
    MAKESTRING="ghc Viewer.hs"
    eval $MAKESTRING
    exit
elif [ "$1" = "h" ]
then
    eval "ghc Viewer.hs -O2 -rtsopts -threaded -prof -fprof-auto"
    cd data
    eval "../Viewer +RTS -s -K200M -N2 -p -h"$2
    eval "hp2ps -c Viewer.hp; cd .."
    exit
else
    echo "ERROR: Argument 1 is wrong (or missing)"
    exit
fi

if [ "$2" = "e" ]
then
    MAKESTRING=$MAKESTRING" -eventlog"
    RUNSTRING=$RUNSTRING" -ls"
elif [ "$2" = "p" ]
then
    MAKESTRING=$MAKESTRING" -prof -fprof-auto"
    RUNSTRING=$RUNSTRING" -p"
elif [ "$2" = "h" ]
then
    MAKESTRING=$MAKESTRING" -prof -fprof-auto"
    cd data
    eval "../Viewer +RTS -s -K200M -N2 -p -h"$3
    eval "hp2ps -c Viewer.hp; cd .."
    exit
elif [ "$2" = "n" ]
then
    : # proceed, no extra options
else
    echo "ERROR: Argument 2 is wrong (or missing)"
    exit
fi

if [ $3 -le 4 ] && [ $3 -ge 1 ]
then
    RUNSTRING=$RUNSTRING" -N"$3
    FILENAME=$FILENAME"_"$3
else
    echo "ERROR: Argument 3 is missing or greater than 4"
    exit
fi

cd data

RUNSTRING=$RUNSTRING" -RTS"
eval $MAKESTRING
eval $RUNSTRING

cd ..
